#!/usr/bin/env bash
#
# Generates LICENSE-3RD-PARTY.txt from the repo's two dependency ecosystems:
#   1. Rust dependencies   -> cargo-about (about.toml / about.hbs)
#   2. Python dependencies -> pip-licenses (runtime dependency closure only)
#
# The two sections are concatenated into a single file at the repo root.
# CI regenerates this file and fails if it differs from the checked-in copy.
#
# Requirements: cargo-about, pip-licenses, and a Python interpreter with the
# package installed. Override the interpreter with PYTHON=/path/to/python.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${ROOT}/LICENSE-3RD-PARTY.txt"
PYTHON="${PYTHON:-python3}"
TMP="$(mktemp)"
trap 'rm -f "${TMP}"' EXIT

cd "${ROOT}"

for tool in cargo cargo-about pip-licenses "${PYTHON}"; do
    command -v "${tool}" >/dev/null 2>&1 || { echo "Required tool not found: ${tool}" >&2; exit 1; }
done

# Runtime dependency closure of the package (one name per line, may be empty).
PY_DEPS=()
while IFS= read -r dep; do
    [[ -n "${dep}" ]] && PY_DEPS+=("${dep}")
done < <("${PYTHON}" scripts/py_runtime_deps.py)

{
    echo "Third-party software notices for atlas-local-lib-py"
    echo
    echo "This file is generated by scripts/generate-third-party.sh."
    echo "Do not edit it by hand; regenerate it and commit the result."
    echo
    echo
    echo "Rust third-party dependencies (cargo)"
    echo "--------------------------------------------------------------------------------"
    echo
    cargo about generate --frozen --config about.toml about.hbs
    echo
    echo 
    echo "Python third-party dependencies (pip)"
    echo "--------------------------------------------------------------------------------"
    echo
    if [[ ${#PY_DEPS[@]} -eq 0 ]]; then
        echo "This project has no third-party Python runtime dependencies."
    else
        pip-licenses \
            --python "${PYTHON}" \
            --packages "${PY_DEPS[@]}" \
            --format=plain-vertical \
            --with-license-file \
            --no-license-path \
            --with-urls \
            --order=name
    fi
} >"${TMP}"

mv "${TMP}" "${OUT}"
trap - EXIT
echo "Wrote ${OUT}"
