# synced from apix-actions/.github/workflows/close-jira.yaml
name: Auto Close Jira

on:
  pull_request:
    types: [closed]

permissions: {}

jobs:
  close-jira:
    if: contains(github.event.pull_request.labels.*.name, 'auto_close_jira')
    permissions:
      contents: read
      pull-requests: read
    uses: mongodb/apix-action/.github/workflows/_close-jira.yaml@b9d203ba30a17b2cae54f9bb2265b4142af38fec
    secrets: inherit