# synced from apix-actions/.github/workflows/dependabot-jira.yaml
name: Create Jira Ticket for Dependabot PRs

on:
  pull_request:
    types: [opened]

permissions: {}

jobs:
  create-jira:
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: read
      pull-requests: write
    uses: mongodb/apix-action/.github/workflows/_dependabot-jira.yaml@de4ebdef39f1941757616df20a791cbd4698aa0c # main
    secrets: inherit