# synced from apix-actions/.github/workflows/issue-closed.yaml
name: Close Jira Ticket on Issue Close

on:
  issues:
    types: [closed]

permissions: {}

jobs:
  close-jira:
    permissions:
      contents: read
      issues: read
    uses: mongodb/apix-action/.github/workflows/_issue-closed.yaml@7a5e504fa3e5d38a29ebe942bd675d6aa7c434c7 # main
    secrets: inherit